name: Build And Deploy to Gh Pages

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    name: Build and Deploy Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          BASE_BRANCH: source
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run-script build