name: Build And Deploy to Gh Pages

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    name: Build and Deploy Source
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        run: npm run-script deploy